#kubectl taint nodes node1 (app=blue): NoSchedule
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: prod
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
  # volumes: #to mount the pod with external volume
  #   - name: data-volume
  #     awsElasticBlockStore:
  #       volumeID: <volume-id>
  #       fsType: ext4
      # envFrom:
      #   - configMapRef:
      #       name: myenv
  # affinity: #this is same as nodeSelector but its more advanced
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: size
  #               operator: #(In/NotIn/Exist)
  #               values:
  #                 - small
  # nodeSelector: #this option is when the pod is being creating it will deployed in node with label size=large (NOTE:DONT USE THIS its old)
  #   size: large
  # tolerations: # here is optional if we want to add taints to the pod so they will be deployed on specific nodes
  #   - key: "app"
  #     operator: "Equal"
  #     value: "blue"
  #     effect: "NoSchedule"
