#replication controller
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: myreplicationctr
#   labels:
#     env: production
# spec:
#   template:
#     metadata:
#      name: nginx-2
#      labels:
#       env: prod
#     spec:
#       containers:
#       - name: nginx
#         image: nginx
      
#   replicas: 3

#replicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicationctr
  labels:
    env: production
spec:
  template:
    metadata:
     name: nginx-2
     labels:
      env: prod
    spec:
      containers:
      - name: nginx
        image: nginx
      
  replicas: 3
  selector:
    matchLabels:
     env: prod