apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-helloworld
  template:
    metadata:
      labels:
        app: my-helloworld
    spec:
      containers:
      - name: my-helloworld-appv2
        image: stacksimplify/kubenginx:2.0.0
        ports:
         - containerPort: 80
