apiVersion: v1
kind: Service
metadata:
  name: deploy-nodeport-service
spec:
  type: NodePort
  selector:
    app: my-helloworld
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31233
